import assert from 'node:assert/strict';
import { readFileSync,mkdirSync,writeFileSync,readdirSync } from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import { pathToFileURL } from 'node:url';
import ts from 'typescript';
import { conversationUrl,launchKey,pickLaunch,validatePayload } from '../companion/shared.js';

mkdirSync('.sites-runtime/launch-tests',{recursive:true});
for(const file of ['task-launch','task-service']){
  const source=readFileSync('app/'+file+'.ts','utf8').replace("'./task-launch'","'./task-launch.mjs'");
  writeFileSync('.sites-runtime/launch-tests/'+file+'.mjs',ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText);
}
const {executeTool,buildState}=await import(pathToFileURL(process.cwd()+'/.sites-runtime/launch-tests/task-service.mjs'));
const sqlite=new DatabaseSync(':memory:');
sqlite.exec('PRAGMA foreign_keys=ON');
for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+file,'utf8'));
function prepare(query){let values=[];return {bind(...v){values=v;return this},async first(){return sqlite.prepare(query).get(...values)||null},async all(){return {results:sqlite.prepare(query).all(...values)}},query,args:()=>values};}
const db={prepare,async batch(statements){sqlite.exec('BEGIN');try{const results=statements.map(s=>/^\s*SELECT/i.test(s.query)?{results:sqlite.prepare(s.query).all(...s.args())}:{results:[],...sqlite.prepare(s.query).run(...s.args())});sqlite.exec('COMMIT');return results;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
const call=(name,args,owner='alice')=>executeTool(db,owner,name,args);
let state=(await call('add_task',{title:'任务 A',taskType:'long_term',startDate:'2026-10-08',durationDays:14,today:'2026-10-08'})).structuredContent;
const a=state.tasks[0].id;
state=(await call('add_task',{title:'任务 B',today:'2026-10-08'})).structuredContent;
const b=state.tasks.find(t=>t.title==='任务 B').id;
await call('save_task_day_entry',{id:a,date:'2026-10-08',plan:'今天标定',workLog:'已采集数据'});
await call('save_daily_report',{date:'2026-10-08',content:'原有复盘正文'});
await call('set_weekly_rest_days',{days:[0]});
const chat='https://chatgpt.com/c/11111111-1111-1111-1111-111111111111';
const work='https://chatgpt.com/c/22222222-2222-2222-2222-222222222222';
const other='https://chatgpt.com/c/33333333-3333-3333-3333-333333333333';
await call('set_task_ai_workspace',{id:a,mode:'chat',url:chat});
await call('set_task_ai_workspace',{id:a,mode:'work',url:work});
await call('set_task_ai_workspace',{id:b,mode:'chat',url:other});
assert.equal((await call('get_task_launch',{id:a,mode:'chat'})).structuredContent.url,chat);
assert.equal((await call('get_task_launch',{id:a,mode:'work'})).structuredContent.url,work);
assert.equal((await call('get_task_launch',{id:b,mode:'chat'})).structuredContent.url,other);
assert.equal((await call('get_task_launch',{id:b,mode:'work'})).structuredContent.url,'');
await call('set_task_ai_workspace',{id:a,mode:'chat'});
assert.equal((await call('get_task_launch',{id:a,mode:'chat'})).structuredContent.url,chat);
await assert.rejects(call('get_task_launch',{id:a,mode:'work'},'bob'),/任务不存在/);
await assert.rejects(call('set_task_ai_workspace',{id:a,mode:'chat',url:'https://chatgpt.com/'}),/首页/);
await assert.rejects(call('set_task_ai_workspace',{id:a,mode:'chat',url:'https://example.com/c/111111111'}),/有效/);
await call('set_task_repository_link',{id:a,url:'https://github.com/example/robot-study.git?tab=readme#top'});
let freshState=await buildState(db,'alice','2026-10-08');
assert.equal(freshState.tasks.find(t=>t.id===a).repositoryLink.url,'https://github.com/example/robot-study');
assert.equal(freshState.tasks.find(t=>t.id===b).repositoryLink.url,'');
await assert.rejects(call('set_task_repository_link',{id:a,url:'https://github.com/example/wrong'},'bob'),/任务不存在/);
await assert.rejects(call('set_task_repository_link',{id:a,url:'javascript:alert(1)'}),/HTTPS/);
await assert.rejects(call('set_task_repository_link',{id:a,url:'https://token:secret@github.com/example/repo'}),/HTTPS/);
await assert.rejects(call('set_task_repository_link',{id:a,url:'https://github.com/'}),/HTTPS/);
await call('set_task_repository_link',{id:a,url:'https://gitlab.com/group/subgroup/robot-study'});
freshState=await buildState(db,'alice','2026-10-08');
assert.equal(freshState.tasks.find(t=>t.id===a).repositoryLink.url,'https://gitlab.com/group/subgroup/robot-study');
const fresh=(await call('get_task_launch',{id:a,mode:'work'})).structuredContent;
assert.ok(fresh.newPrompt.includes('https://gitlab.com/group/subgroup/robot-study'));
for(const action of ['publish','commit_push','status','diff','log','pull','branch'])await assert.rejects(call('get_task_launch',{id:a,mode:'work',action}));
await call('set_task_repository_link',{id:a,url:''});
assert.equal((await buildState(db,'alice','2026-10-08')).tasks.find(t=>t.id===a).repositoryLink.url,'');
const html=readFileSync('app/dashboard.html','utf8');
assert.ok(html.includes('data-open-repository'));assert.ok(html.includes('打开仓库'));
assert.ok(!html.includes('data-work-git-action'));assert.ok(!html.includes('data-gh-action'));assert.ok(!html.includes('local-git-path'));
const after=await buildState(db,'alice','2026-10-08');
assert.equal(after.tasks.find(t=>t.id===a).dailyEntries[0].workLog,'已采集数据');
assert.equal(after.reports[0].content,'原有复盘正文');assert.deepEqual(after.settings.weeklyRestDays,[0]);
assert.equal(conversationUrl('https://chatgpt.com/'),'');assert.equal(conversationUrl('javascript:alert(1)'),'');
assert.notEqual(launchKey(a,'chat'),launchKey(a,'work'));assert.notEqual(launchKey(a,'chat'),launchKey(b,'chat'));
const payload=validatePayload({...fresh,forceNew:false});
assert.equal(pickLaunch(payload,null,{}).url,work);
const rebuilt=pickLaunch(payload,null,{[work]:Date.now()});assert.equal(rebuilt.existing,'');assert.equal(new URL(rebuilt.url).searchParams.get('surface'),'work');
assert.equal(new URL(rebuilt.url).searchParams.has('prompt'),false,'Task context is sent through the composer, never a long URL');
assert.equal(rebuilt.prompt,fresh.newPrompt);
assert.equal(pickLaunch({...payload,forceNew:true},null,{}).existing,'');
assert.equal(pickLaunch({...payload,url:''},{url:work},{}).existing,work);
assert.ok(fresh.bindingUpdatedAt,'Persisted bindings include their update time');
assert.equal(pickLaunch(payload,{url:other,updatedAt:Date.now()+1000,unpersisted:true},{}).existing,other,'Recover a newer binding even when its launcher closed before the server write');
assert.equal(pickLaunch({...payload,bindingUpdatedAt:new Date(Date.now()+2000).toISOString()},{url:other,updatedAt:Date.now(),unpersisted:true},{}).existing,work,'A newer explicit server binding wins over the recovery copy');
assert.equal(pickLaunch(payload,{url:other},{[work]:Date.now()}).existing,other,'Use the replacement binding when the old server conversation was deleted');
console.log('PASS: independent task/mode bindings, durable reads, owner isolation, homepage rejection, repository links and removed Git actions, deletion rebuild, legacy task/report preservation.');
